version: '3.8'

services:
  laravel10-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: laravel10-app
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel10-network

  nginx:
    image: nginx:latest
    container_name: laravel10-nginx
    ports:
      - "8020:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel10-app
    networks:
      - laravel10-network

  mysql:
    image: mysql:8.0
    container_name: laravel10-mysql
    environment:
      MYSQL_ROOT_PASSWORD: laravel10-app
      MYSQL_DATABASE: laravel10-app
      MYSQL_USER: laravel10-app
      MYSQL_PASSWORD: laravel10-app
    volumes:
      - dbdata-laravel10-app:/var/lib/mysql
    networks:
      - laravel10-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: laravel10-phpmyadmin
    environment:
      PMA_HOST: mysql  # MySQL container hostname
      MYSQL_ROOT_PASSWORD: laravel10-app
    ports:
      - "8021:80"  # Access phpMyAdmin at http://localhost:8021
    depends_on:
      - mysql
    networks:
      - laravel10-network

networks:
  laravel10-network:

volumes:
  dbdata-laravel10-app:
